name: news_letter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  json_annotation: ^4.8.1
  retrofit_generator: ^7.0.1
  retrofit: ^4.0.1
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  internet_connection_checker_plus: ^1.0.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
